keycloak:
  container_name: keycloak
  image: quay.io/keycloak/keycloak:15.0.2
  ports:
  - "8080:8080"
  volumes:
  - ./theme_1qos/:/opt/jboss/keycloak/themes/theme_1qos/
  environment:
    KEYCLOAK_ENVIRONMENT: "/etc/secrets/keycloak.env"
    KEYCLOAK_PASSWORD: "admin"
    KEYCLOAK_USER: "admin"
  command:
  - -b 0.0.0.0 --server-config=standalone.xml